### PR TITLE
chore(deps): fix security warnings

### PR DESCRIPTION
**Pull request by ev1stensberg**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Security

### Breaking Changes

n/a

### Additional Info

n/a

### CODE REVIEW

**Comment by shellscape** [comment]
@ev1stensberg running `npm run security` shows no security concerns. Please elaborate on this PR

**Comment by ev1stensberg** [comment]
Run npm install and see the security warnings

**Comment by shellscape** [comment]
I get no security warnings on the latest npm. In contrib we ask that contributors be verbose. Please copy and paste the warnings you're receiving as well as the version of NPM you're seeing that on.

**Comment by shellscape** [comment]
@ev1stensberg here's the output I get:

```console
→ rm -rf node_modules && npm install

> fsevents@1.2.3 install /.../code/webpack-command/node_modules/fsevents
> node install

[fsevents] Success: "/.../code/webpack-command/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> husky@0.14.3 install /.../code/webpack-command/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
skippingpre-commit hook (existing user hook)
done


> pre-commit@1.2.2 install /.../code/webpack-command/node_modules/pre-commit
> node install.js

pre-commit:
pre-commit: Detected an existing git pre-commit hook
pre-commit: Old pre-commit hook backuped to pre-commit.old
pre-commit:

> spawn-sync@1.0.15 postinstall /.../code/webpack-command/node_modules/spawn-sync
> node postinstall


> webpack-defaults@2.3.0 postinstall /.../code/webpack-command/node_modules/webpack-defaults
> node lib/post_install.js

(node:30080) ExperimentalWarning: The fs.promises API is experimental
added 1763 packages in 15.257s
```

**Comment by ev1stensberg** [comment]
Do a clean install without package lock

**Comment by shellscape** [comment]
Sorry, but I've asked a few times for some output and elaboration. Not sure why you're resisting that; I feel I've been pretty reasonable and provided the same output I've been asking for. The only package dependency updates are for `devDependencies` and those should be submitted via `package.json` and not `package-lock.json`, at which point we'd generate a new lockfile. There's also the mentioned version downgrades in `package-lock.json`. It's also peculiar that you'd be receiving security notices without a lockfile because the lockfile is part of the repo and should be present when cloning.

This PR is a little funky, so I'm going to pass on it for now.

**Comment by ev1stensberg** [comment]
No worries, just trying to help

**Pull request closed without merging**
